In [1]:
import pandas as pd
import numpy as np

In [41]:
A = [ 2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2, 1, 1.5, 1.1 ]


In [42]:
A_mean = np.sum(A)/ len(A)
print(A_mean)

1.81


In [43]:
B = [ 2.4, 0.7, 2.9, 2.2, 3, 2.7, 1.6, 1.1, 1.6, 0.9]

In [56]:
B_mean = np.sum(B) / len(B)
print(B_mean)


1.9100000000000001


In [58]:
A1 = A - A_mean
print(A1)

[ 0.69 -1.31  0.39  0.09  1.29  0.49  0.19 -0.81 -0.31 -0.71]


In [59]:
B1 = B - B_mean
print(B1)

[ 0.49 -1.21  0.99  0.29  1.09  0.79 -0.31 -0.81 -0.31 -1.01]


In [63]:
A1A1 = np.multiply(A1,A1)
print(A1A1)

[0.4761 1.7161 0.1521 0.0081 1.6641 0.2401 0.0361 0.6561 0.0961 0.5041]


In [64]:
B1B1 = np.multiply(B1,B1)
print(B1B1)

[0.2401 1.4641 0.9801 0.0841 1.1881 0.6241 0.0961 0.6561 0.0961 1.0201]


In [66]:
A1B1 = np.multiply(A1,B1)
print(A1B1)

[ 0.3381  1.5851  0.3861  0.0261  1.4061  0.3871 -0.0589  0.6561  0.0961
  0.7171]


In [73]:
A1A1_mean = np.sum(A1A1) / (len(A) - 1)
print(A1A1_mean)


0.6165555555555556


In [75]:
B1B1_mean = np.sum(B1B1) / (len(A) - 1)
print(B1B1_mean)

0.7165555555555555


In [76]:
A1B1_mean = np.sum(A1B1) / (len(A) - 1)
print(A1B1_mean)

0.6154444444444445


In [79]:
import math

In [78]:
# C = [[A1A1_mean, A1B1_mean],
#     [A1B1_mean, B1B1_mean]]
# Eigen Values : C - lamba*I = 0
# (A1A1_mean - lambda) * (B1B1_mean - lambda) - (A1B1_mean * A1B1_mean) = 0
# lambda*lambda + A1A1_mean*B1B1_mean - lambda * (A1A1_mean + B1B1_mean) - (A1B1_mean * A1B1_mean) = 0

In [94]:
a = 1
b = -( A1A1_mean + B1B1_mean)
print(b)
c =  A1A1_mean*B1B1_mean - A1B1_mean*A1B1_mean
print(c)

-1.3331111111111111
0.06302444444444444


In [97]:
lambda1 = ( -b + ( math.sqrt( b*b - 4*a*c) ) ) /2*a
lambda2 = ( -b - ( math.sqrt( b*b - 4*a*c) ) ) /2*a
# lambda1 = ( (A1A1_mean + B1B1_mean) + math.sqrt(   (A1A1_mean + B1B1_mean)*(A1A1_mean + B1B1_mean) + (4*(A1B1_mean * A1B1_mean))   ) ) / 2
# lambda2 = ( (A1A1_mean + B1B1_mean) - math.sqrt(   (A1A1_mean + B1B1_mean)*(A1A1_mean + B1B1_mean) + (4*(A1B1_mean * A1B1_mean))   ) ) / 2

In [98]:
print(lambda1)
print(lambda2)

1.2840277121727839
0.04908339893832725


In [ ]:
#  ( C - lambda1*I ) * U1 = 0
# U1 = [u1, u2], U2 = [u1 , u2]

In [104]:
t1=1

In [105]:
u1 = t1 * ( - A1B1_mean )
u2 = t1 * ( A1A1_mean - lambda1)
U1 = [u1, u2]
print(U1)

[-0.6154444444444445, -0.6674721566172283]


In [106]:
# Normalisation
denominator_U1 = math.sqrt( u1*u1 + u2*u2 )
e1 = [ u1/denominator_U1, u2/denominator_U1]
print(e1)

[-0.6778733985280118, -0.7351786555444081]


In [107]:
u1 = t1 * ( - A1B1_mean )
u2 = t1 * ( A1A1_mean - lambda2)
U2 = [u1, u2]
print(U2)

[-0.6154444444444445, 0.5674721566172284]


In [109]:
# Normalisation
denominator_U2 = math.sqrt( u1*u1 + u2*u2 )
e2 = [ u1/denominator_U2, u2/denominator_U2]
print(e2)

[-0.7351786555444081, 0.6778733985280118]


# OUTPUT

## New Mapped Datasets

In [113]:
PCA1 = e1[0]*A1 + e1[1]*B1
print(PCA1)

[-0.82797019  1.77758033 -0.99219749 -0.27421042 -1.67580142 -0.9129491
  0.09910944  1.14457216  0.43804614  1.22382056]


In [114]:
PCA2 = e2[0]*A1 + e2[1]*B1
print(PCA2)

[-0.17511531  0.14285723  0.38437499  0.13041721 -0.20949846  0.17528244
 -0.3498247   0.04641726  0.01776463 -0.16267529]
